# Generated by Django 3.2.18 on 2023-03-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='license_key',
            field=models.UUIDField(null=True),
        ),
    ]
